apiVersion: v1
kind: Service
metadata:
  name: oauth2-server
  labels:
    app: oauth2-server
spec:
  type: NodePort
  selector:
    app: oauth2-server
  ports:
  - port: 80         # Service port
    targetPort: 8080 # Container port
